package gov.nasa.jpl.pyre.spark.resources.discrete

import gov.nasa.jpl.pyre.coals.curry
import gov.nasa.jpl.pyre.ember.Duration
import gov.nasa.jpl.pyre.spark.resources.Dynamics
import gov.nasa.jpl.pyre.spark.resources.DynamicsMonad
import gov.nasa.jpl.pyre.spark.resources.FullDynamics
import gov.nasa.jpl.pyre.spark.resources.MutableResource
import gov.nasa.jpl.pyre.spark.resources.Resource
import gov.nasa.jpl.pyre.spark.resources.ResourceMonad

data class Discrete<A>(val value: A) : Dynamics<A, Discrete<A>> {
    override fun value() = value
    override fun step(t: Duration) = this
}

typealias DiscreteResource<V> = Resource<Discrete<V>>
typealias MutableDiscreteResource<V> = MutableResource<Discrete<V>>

object DiscreteMonad {
    fun <A> pure(a: A): Discrete<A> = Discrete(a)
    fun <A, B> apply(a: Discrete<A>, f: Discrete<(A) -> B>): Discrete<B> = Discrete(f.value(a.value))
    fun <A> join(a: Discrete<Discrete<A>>): Discrete<A> = a.value
    // Auxiliary methods - These are defined only in terms of pure/apply/join above, and can be copied from Monad to Monad
    fun <A, B> apply(f: Discrete<(A) -> B>): (Discrete<A>) -> Discrete<B> = { apply(it, f) }
    fun <A, B> map(a: Discrete<A>, f: (A) -> B): Discrete<B> = apply(a, pure(f))
    fun <A, B> map(f: (A) -> B): (Discrete<A>) -> Discrete<B> = { map(it, f) }
    fun <A, B> bind(a: Discrete<A>, f: (A) -> Discrete<B>): Discrete<B> = join(map(a, f))
    fun <A, B> bind(f: (A) -> Discrete<B>): (Discrete<A>) -> Discrete<B> = { bind(it, f) }
    // Auxiliary map
    fun <A, B, C> map(fn: (A, B) -> C): (Discrete<A>, Discrete<B>) -> Discrete<C> = { a, b -> map(a, b, fn) }
    fun <A, B, C> map(a: Discrete<A>, b: Discrete<B>, fn: (A, B) -> C): Discrete<C> = map(a, b, curry(fn))
    fun <A, B, C> map(a: Discrete<A>, b: Discrete<B>, fn: (A) -> (B) -> C): Discrete<C> = apply(b, map(a, fn))
    fun <A, B, C, D> map(fn: (A, B, C) -> D): (Discrete<A>, Discrete<B>, Discrete<C>) -> Discrete<D> = { a, b, c -> map(a, b, c, fn) }
    fun <A, B, C, D> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, fn: (A, B, C) -> D): Discrete<D> = map(a, b, c, curry(fn))
    fun <A, B, C, D> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, fn: (A) -> (B) -> (C) -> D): Discrete<D> = apply(c, map(a, b, fn))
    fun <A, B, C, D, E> map(fn: (A, B, C, D) -> E): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>) -> Discrete<E> = { a, b, c, d -> map(a, b, c, d, fn) }
    fun <A, B, C, D, E> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, fn: (A, B, C, D) -> E): Discrete<E> = map(a, b, c, d, curry(fn))
    fun <A, B, C, D, E> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, fn: (A) -> (B) -> (C) -> (D) -> E): Discrete<E> = apply(d, map(a, b, c, fn))
    fun <A, B, C, D, E, F> map(fn: (A, B, C, D, E) -> F): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>) -> Discrete<F> = { a, b, c, d, e -> map(a, b, c, d, e, fn) }
    fun <A, B, C, D, E, F> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, fn: (A, B, C, D, E) -> F): Discrete<F> = map(a, b, c, d, e, curry(fn))
    fun <A, B, C, D, E, F> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> F): Discrete<F> = apply(e, map(a, b, c, d, fn))
    fun <A, B, C, D, E, F, G> map(fn: (A, B, C, D, E, F) -> G): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>) -> Discrete<G> = { a, b, c, d, e, f -> map(a, b, c, d, e, f, fn) }
    fun <A, B, C, D, E, F, G> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, fn: (A, B, C, D, E, F) -> G): Discrete<G> = map(a, b, c, d, e, f, curry(fn))
    fun <A, B, C, D, E, F, G> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> G): Discrete<G> = apply(f, map(a, b, c, d, e, fn))
    fun <A, B, C, D, E, F, G, H> map(fn: (A, B, C, D, E, F, G) -> H): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>) -> Discrete<H> = { a, b, c, d, e, f, g -> map(a, b, c, d, e, f, g, fn) }
    fun <A, B, C, D, E, F, G, H> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, fn: (A, B, C, D, E, F, G) -> H): Discrete<H> = map(a, b, c, d, e, f, g, curry(fn))
    fun <A, B, C, D, E, F, G, H> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> H): Discrete<H> = apply(g, map(a, b, c, d, e, f, fn))
    fun <A, B, C, D, E, F, G, H, I> map(fn: (A, B, C, D, E, F, G, H) -> I): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>) -> Discrete<I> = { a, b, c, d, e, f, g, h -> map(a, b, c, d, e, f, g, h, fn) }
    fun <A, B, C, D, E, F, G, H, I> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, fn: (A, B, C, D, E, F, G, H) -> I): Discrete<I> = map(a, b, c, d, e, f, g, h, curry(fn))
    fun <A, B, C, D, E, F, G, H, I> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> I): Discrete<I> = apply(h, map(a, b, c, d, e, f, g, fn))
    fun <A, B, C, D, E, F, G, H, I, J> map(fn: (A, B, C, D, E, F, G, H, I) -> J): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>) -> Discrete<J> = { a, b, c, d, e, f, g, h, i -> map(a, b, c, d, e, f, g, h, i, fn) }
    fun <A, B, C, D, E, F, G, H, I, J> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, fn: (A, B, C, D, E, F, G, H, I) -> J): Discrete<J> = map(a, b, c, d, e, f, g, h, i, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> J): Discrete<J> = apply(i, map(a, b, c, d, e, f, g, h, fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> map(fn: (A, B, C, D, E, F, G, H, I, J) -> K): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>) -> Discrete<K> = { a, b, c, d, e, f, g, h, i, j -> map(a, b, c, d, e, f, g, h, i, j, fn) }
    fun <A, B, C, D, E, F, G, H, I, J, K> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, j: Discrete<J>, fn: (A, B, C, D, E, F, G, H, I, J) -> K): Discrete<K> = map(a, b, c, d, e, f, g, h, i, j, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> map(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, j: Discrete<J>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> K): Discrete<K> = apply(j, map(a, b, c, d, e, f, g, h, i, fn))
    // Auxiliary bind
    fun <A, B, C> bind(fn: (A, B) -> Discrete<C>): (Discrete<A>, Discrete<B>) -> Discrete<C> = { a, b -> bind(a, b, fn) }
    fun <A, B, C> bind(a: Discrete<A>, b: Discrete<B>, fn: (A, B) -> Discrete<C>): Discrete<C> = bind(a, b, curry(fn))
    fun <A, B, C> bind(a: Discrete<A>, b: Discrete<B>, fn: (A) -> (B) -> Discrete<C>): Discrete<C> = join(map(a, b, fn))
    fun <A, B, C, D> bind(fn: (A, B, C) -> Discrete<D>): (Discrete<A>, Discrete<B>, Discrete<C>) -> Discrete<D> = { a, b, c -> bind(a, b, c, fn) }
    fun <A, B, C, D> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, fn: (A, B, C) -> Discrete<D>): Discrete<D> = bind(a, b, c, curry(fn))
    fun <A, B, C, D> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, fn: (A) -> (B) -> (C) -> Discrete<D>): Discrete<D> = join(map(a, b, c, fn))
    fun <A, B, C, D, E> bind(fn: (A, B, C, D) -> Discrete<E>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>) -> Discrete<E> = { a, b, c, d -> bind(a, b, c, d, fn) }
    fun <A, B, C, D, E> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, fn: (A, B, C, D) -> Discrete<E>): Discrete<E> = bind(a, b, c, d, curry(fn))
    fun <A, B, C, D, E> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, fn: (A) -> (B) -> (C) -> (D) -> Discrete<E>): Discrete<E> = join(map(a, b, c, d, fn))
    fun <A, B, C, D, E, F> bind(fn: (A, B, C, D, E) -> Discrete<F>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>) -> Discrete<F> = { a, b, c, d, e -> bind(a, b, c, d, e, fn) }
    fun <A, B, C, D, E, F> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, fn: (A, B, C, D, E) -> Discrete<F>): Discrete<F> = bind(a, b, c, d, e, curry(fn))
    fun <A, B, C, D, E, F> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> Discrete<F>): Discrete<F> = join(map(a, b, c, d, e, fn))
    fun <A, B, C, D, E, F, G> bind(fn: (A, B, C, D, E, F) -> Discrete<G>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>) -> Discrete<G> = { a, b, c, d, e, f -> bind(a, b, c, d, e, f, fn) }
    fun <A, B, C, D, E, F, G> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, fn: (A, B, C, D, E, F) -> Discrete<G>): Discrete<G> = bind(a, b, c, d, e, f, curry(fn))
    fun <A, B, C, D, E, F, G> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> Discrete<G>): Discrete<G> = join(map(a, b, c, d, e, f, fn))
    fun <A, B, C, D, E, F, G, H> bind(fn: (A, B, C, D, E, F, G) -> Discrete<H>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>) -> Discrete<H> = { a, b, c, d, e, f, g -> bind(a, b, c, d, e, f, g, fn) }
    fun <A, B, C, D, E, F, G, H> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, fn: (A, B, C, D, E, F, G) -> Discrete<H>): Discrete<H> = bind(a, b, c, d, e, f, g, curry(fn))
    fun <A, B, C, D, E, F, G, H> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> Discrete<H>): Discrete<H> = join(map(a, b, c, d, e, f, g, fn))
    fun <A, B, C, D, E, F, G, H, I> bind(fn: (A, B, C, D, E, F, G, H) -> Discrete<I>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>) -> Discrete<I> = { a, b, c, d, e, f, g, h -> bind(a, b, c, d, e, f, g, h, fn) }
    fun <A, B, C, D, E, F, G, H, I> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, fn: (A, B, C, D, E, F, G, H) -> Discrete<I>): Discrete<I> = bind(a, b, c, d, e, f, g, h, curry(fn))
    fun <A, B, C, D, E, F, G, H, I> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> Discrete<I>): Discrete<I> = join(map(a, b, c, d, e, f, g, h, fn))
    fun <A, B, C, D, E, F, G, H, I, J> bind(fn: (A, B, C, D, E, F, G, H, I) -> Discrete<J>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>) -> Discrete<J> = { a, b, c, d, e, f, g, h, i -> bind(a, b, c, d, e, f, g, h, i, fn) }
    fun <A, B, C, D, E, F, G, H, I, J> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, fn: (A, B, C, D, E, F, G, H, I) -> Discrete<J>): Discrete<J> = bind(a, b, c, d, e, f, g, h, i, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> Discrete<J>): Discrete<J> = join(map(a, b, c, d, e, f, g, h, i, fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(fn: (A, B, C, D, E, F, G, H, I, J) -> Discrete<K>): (Discrete<A>, Discrete<B>, Discrete<C>, Discrete<D>, Discrete<E>, Discrete<F>, Discrete<G>, Discrete<H>, Discrete<I>, Discrete<J>) -> Discrete<K> = { a, b, c, d, e, f, g, h, i, j -> bind(a, b, c, d, e, f, g, h, i, j, fn) }
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, j: Discrete<J>, fn: (A, B, C, D, E, F, G, H, I, J) -> Discrete<K>): Discrete<K> = bind(a, b, c, d, e, f, g, h, i, j, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(a: Discrete<A>, b: Discrete<B>, c: Discrete<C>, d: Discrete<D>, e: Discrete<E>, f: Discrete<F>, g: Discrete<G>, h: Discrete<H>, i: Discrete<I>, j: Discrete<J>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> Discrete<K>): Discrete<K> = join(map(a, b, c, d, e, f, g, h, i, j, fn))
}

object DiscreteDynamicsMonad {
    fun <A> pure(a: A): FullDynamics<Discrete<A>> = DynamicsMonad.pure(DiscreteMonad.pure(a))
    fun <A, B> apply(a: FullDynamics<Discrete<A>>, f: FullDynamics<Discrete<(A) -> B>>): FullDynamics<Discrete<B>> =
        DynamicsMonad.apply(a, DynamicsMonad.map(f, DiscreteMonad::apply))
    fun <A> distribute(a: Discrete<FullDynamics<A>>): FullDynamics<Discrete<A>> =
        DynamicsMonad.map(a.value, DiscreteMonad::pure)
    fun <A> join(a: FullDynamics<Discrete<FullDynamics<Discrete<A>>>>): FullDynamics<Discrete<A>> =
        DynamicsMonad.map(DynamicsMonad.join(DynamicsMonad.map(a, DiscreteDynamicsMonad::distribute)), DiscreteMonad::join)
    // Auxiliary methods - These are defined only in terms of pure/apply/join above, and can be copied from Monad to Monad
    fun <A, B> apply(f: FullDynamics<Discrete<(A) -> B>>): (FullDynamics<Discrete<A>>) -> FullDynamics<Discrete<B>> = { apply(it, f) }
    fun <A, B> map(a: FullDynamics<Discrete<A>>, f: (A) -> B): FullDynamics<Discrete<B>> = apply(a, pure(f))
    fun <A, B> map(f: (A) -> B): (FullDynamics<Discrete<A>>) -> FullDynamics<Discrete<B>> = { map(it, f) }
    fun <A, B> bind(a: FullDynamics<Discrete<A>>, f: (A) -> FullDynamics<Discrete<B>>): FullDynamics<Discrete<B>> = join(map(a, f))
    fun <A, B> bind(f: (A) -> FullDynamics<Discrete<B>>): (FullDynamics<Discrete<A>>) -> FullDynamics<Discrete<B>> = { bind(it, f) }
    // Auxiliary map
    fun <A, B, C> map(fn: (A, B) -> C): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>) -> FullDynamics<Discrete<C>> = { a, b -> map(a, b, fn) }
    fun <A, B, C> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, fn: (A, B) -> C): FullDynamics<Discrete<C>> = map(a, b, curry(fn))
    fun <A, B, C> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, fn: (A) -> (B) -> C): FullDynamics<Discrete<C>> = apply(b, map(a, fn))
    fun <A, B, C, D> map(fn: (A, B, C) -> D): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>) -> FullDynamics<Discrete<D>> = { a, b, c -> map(a, b, c, fn) }
    fun <A, B, C, D> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, fn: (A, B, C) -> D): FullDynamics<Discrete<D>> = map(a, b, c, curry(fn))
    fun <A, B, C, D> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, fn: (A) -> (B) -> (C) -> D): FullDynamics<Discrete<D>> = apply(c, map(a, b, fn))
    fun <A, B, C, D, E> map(fn: (A, B, C, D) -> E): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>) -> FullDynamics<Discrete<E>> = { a, b, c, d -> map(a, b, c, d, fn) }
    fun <A, B, C, D, E> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, fn: (A, B, C, D) -> E): FullDynamics<Discrete<E>> = map(a, b, c, d, curry(fn))
    fun <A, B, C, D, E> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, fn: (A) -> (B) -> (C) -> (D) -> E): FullDynamics<Discrete<E>> = apply(d, map(a, b, c, fn))
    fun <A, B, C, D, E, F> map(fn: (A, B, C, D, E) -> F): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>) -> FullDynamics<Discrete<F>> = { a, b, c, d, e -> map(a, b, c, d, e, fn) }
    fun <A, B, C, D, E, F> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, fn: (A, B, C, D, E) -> F): FullDynamics<Discrete<F>> = map(a, b, c, d, e, curry(fn))
    fun <A, B, C, D, E, F> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> F): FullDynamics<Discrete<F>> = apply(e, map(a, b, c, d, fn))
    fun <A, B, C, D, E, F, G> map(fn: (A, B, C, D, E, F) -> G): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>) -> FullDynamics<Discrete<G>> = { a, b, c, d, e, f -> map(a, b, c, d, e, f, fn) }
    fun <A, B, C, D, E, F, G> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, fn: (A, B, C, D, E, F) -> G): FullDynamics<Discrete<G>> = map(a, b, c, d, e, f, curry(fn))
    fun <A, B, C, D, E, F, G> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> G): FullDynamics<Discrete<G>> = apply(f, map(a, b, c, d, e, fn))
    fun <A, B, C, D, E, F, G, H> map(fn: (A, B, C, D, E, F, G) -> H): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>) -> FullDynamics<Discrete<H>> = { a, b, c, d, e, f, g -> map(a, b, c, d, e, f, g, fn) }
    fun <A, B, C, D, E, F, G, H> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, fn: (A, B, C, D, E, F, G) -> H): FullDynamics<Discrete<H>> = map(a, b, c, d, e, f, g, curry(fn))
    fun <A, B, C, D, E, F, G, H> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> H): FullDynamics<Discrete<H>> = apply(g, map(a, b, c, d, e, f, fn))
    fun <A, B, C, D, E, F, G, H, I> map(fn: (A, B, C, D, E, F, G, H) -> I): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>, FullDynamics<Discrete<H>>) -> FullDynamics<Discrete<I>> = { a, b, c, d, e, f, g, h -> map(a, b, c, d, e, f, g, h, fn) }
    fun <A, B, C, D, E, F, G, H, I> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, fn: (A, B, C, D, E, F, G, H) -> I): FullDynamics<Discrete<I>> = map(a, b, c, d, e, f, g, h, curry(fn))
    fun <A, B, C, D, E, F, G, H, I> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> I): FullDynamics<Discrete<I>> = apply(h, map(a, b, c, d, e, f, g, fn))
    fun <A, B, C, D, E, F, G, H, I, J> map(fn: (A, B, C, D, E, F, G, H, I) -> J): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>, FullDynamics<Discrete<H>>, FullDynamics<Discrete<I>>) -> FullDynamics<Discrete<J>> = { a, b, c, d, e, f, g, h, i -> map(a, b, c, d, e, f, g, h, i, fn) }
    fun <A, B, C, D, E, F, G, H, I, J> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, fn: (A, B, C, D, E, F, G, H, I) -> J): FullDynamics<Discrete<J>> = map(a, b, c, d, e, f, g, h, i, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> J): FullDynamics<Discrete<J>> = apply(i, map(a, b, c, d, e, f, g, h, fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> map(fn: (A, B, C, D, E, F, G, H, I, J) -> K): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>, FullDynamics<Discrete<H>>, FullDynamics<Discrete<I>>, FullDynamics<Discrete<J>>) -> FullDynamics<Discrete<K>> = { a, b, c, d, e, f, g, h, i, j -> map(a, b, c, d, e, f, g, h, i, j, fn) }
    fun <A, B, C, D, E, F, G, H, I, J, K> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, j: FullDynamics<Discrete<J>>, fn: (A, B, C, D, E, F, G, H, I, J) -> K): FullDynamics<Discrete<K>> = map(a, b, c, d, e, f, g, h, i, j, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> map(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, j: FullDynamics<Discrete<J>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> K): FullDynamics<Discrete<K>> = apply(j, map(a, b, c, d, e, f, g, h, i, fn))
    // Auxiliary bind
    fun <A, B, C> bind(fn: (A, B) -> FullDynamics<Discrete<C>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>) -> FullDynamics<Discrete<C>> = { a, b -> bind(a, b, fn) }
    fun <A, B, C> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, fn: (A, B) -> FullDynamics<Discrete<C>>): FullDynamics<Discrete<C>> = bind(a, b, curry(fn))
    fun <A, B, C> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, fn: (A) -> (B) -> FullDynamics<Discrete<C>>): FullDynamics<Discrete<C>> = join(map(a, b, fn))
    fun <A, B, C, D> bind(fn: (A, B, C) -> FullDynamics<Discrete<D>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>) -> FullDynamics<Discrete<D>> = { a, b, c -> bind(a, b, c, fn) }
    fun <A, B, C, D> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, fn: (A, B, C) -> FullDynamics<Discrete<D>>): FullDynamics<Discrete<D>> = bind(a, b, c, curry(fn))
    fun <A, B, C, D> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, fn: (A) -> (B) -> (C) -> FullDynamics<Discrete<D>>): FullDynamics<Discrete<D>> = join(map(a, b, c, fn))
    fun <A, B, C, D, E> bind(fn: (A, B, C, D) -> FullDynamics<Discrete<E>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>) -> FullDynamics<Discrete<E>> = { a, b, c, d -> bind(a, b, c, d, fn) }
    fun <A, B, C, D, E> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, fn: (A, B, C, D) -> FullDynamics<Discrete<E>>): FullDynamics<Discrete<E>> = bind(a, b, c, d, curry(fn))
    fun <A, B, C, D, E> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, fn: (A) -> (B) -> (C) -> (D) -> FullDynamics<Discrete<E>>): FullDynamics<Discrete<E>> = join(map(a, b, c, d, fn))
    fun <A, B, C, D, E, F> bind(fn: (A, B, C, D, E) -> FullDynamics<Discrete<F>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>) -> FullDynamics<Discrete<F>> = { a, b, c, d, e -> bind(a, b, c, d, e, fn) }
    fun <A, B, C, D, E, F> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, fn: (A, B, C, D, E) -> FullDynamics<Discrete<F>>): FullDynamics<Discrete<F>> = bind(a, b, c, d, e, curry(fn))
    fun <A, B, C, D, E, F> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> FullDynamics<Discrete<F>>): FullDynamics<Discrete<F>> = join(map(a, b, c, d, e, fn))
    fun <A, B, C, D, E, F, G> bind(fn: (A, B, C, D, E, F) -> FullDynamics<Discrete<G>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>) -> FullDynamics<Discrete<G>> = { a, b, c, d, e, f -> bind(a, b, c, d, e, f, fn) }
    fun <A, B, C, D, E, F, G> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, fn: (A, B, C, D, E, F) -> FullDynamics<Discrete<G>>): FullDynamics<Discrete<G>> = bind(a, b, c, d, e, f, curry(fn))
    fun <A, B, C, D, E, F, G> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> FullDynamics<Discrete<G>>): FullDynamics<Discrete<G>> = join(map(a, b, c, d, e, f, fn))
    fun <A, B, C, D, E, F, G, H> bind(fn: (A, B, C, D, E, F, G) -> FullDynamics<Discrete<H>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>) -> FullDynamics<Discrete<H>> = { a, b, c, d, e, f, g -> bind(a, b, c, d, e, f, g, fn) }
    fun <A, B, C, D, E, F, G, H> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, fn: (A, B, C, D, E, F, G) -> FullDynamics<Discrete<H>>): FullDynamics<Discrete<H>> = bind(a, b, c, d, e, f, g, curry(fn))
    fun <A, B, C, D, E, F, G, H> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> FullDynamics<Discrete<H>>): FullDynamics<Discrete<H>> = join(map(a, b, c, d, e, f, g, fn))
    fun <A, B, C, D, E, F, G, H, I> bind(fn: (A, B, C, D, E, F, G, H) -> FullDynamics<Discrete<I>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>, FullDynamics<Discrete<H>>) -> FullDynamics<Discrete<I>> = { a, b, c, d, e, f, g, h -> bind(a, b, c, d, e, f, g, h, fn) }
    fun <A, B, C, D, E, F, G, H, I> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, fn: (A, B, C, D, E, F, G, H) -> FullDynamics<Discrete<I>>): FullDynamics<Discrete<I>> = bind(a, b, c, d, e, f, g, h, curry(fn))
    fun <A, B, C, D, E, F, G, H, I> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> FullDynamics<Discrete<I>>): gov.nasa.jpl.pyre.spark.resources.FullDynamics<gov.nasa.jpl.pyre.spark.resources.discrete.Discrete<I>> = join(map(a, b, c, d, e, f, g, h, fn))
    fun <A, B, C, D, E, F, G, H, I, J> bind(fn: (A, B, C, D, E, F, G, H, I) -> FullDynamics<Discrete<J>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>, FullDynamics<Discrete<H>>, FullDynamics<Discrete<I>>) -> FullDynamics<Discrete<J>> = { a, b, c, d, e, f, g, h, i -> bind(a, b, c, d, e, f, g, h, i, fn) }
    fun <A, B, C, D, E, F, G, H, I, J> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, fn: (A, B, C, D, E, F, G, H, I) -> FullDynamics<Discrete<J>>): FullDynamics<Discrete<J>> = bind(a, b, c, d, e, f, g, h, i, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> FullDynamics<Discrete<J>>): FullDynamics<Discrete<J>> = join(map(a, b, c, d, e, f, g, h, i, fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(fn: (A, B, C, D, E, F, G, H, I, J) -> FullDynamics<Discrete<K>>): (FullDynamics<Discrete<A>>, FullDynamics<Discrete<B>>, FullDynamics<Discrete<C>>, FullDynamics<Discrete<D>>, FullDynamics<Discrete<E>>, FullDynamics<Discrete<F>>, FullDynamics<Discrete<G>>, FullDynamics<Discrete<H>>, FullDynamics<Discrete<I>>, FullDynamics<Discrete<J>>) -> FullDynamics<Discrete<K>> = { a, b, c, d, e, f, g, h, i, j -> bind(a, b, c, d, e, f, g, h, i, j, fn) }
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, j: FullDynamics<Discrete<J>>, fn: (A, B, C, D, E, F, G, H, I, J) -> FullDynamics<Discrete<K>>): FullDynamics<Discrete<K>> = bind(a, b, c, d, e, f, g, h, i, j, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(a: FullDynamics<Discrete<A>>, b: FullDynamics<Discrete<B>>, c: FullDynamics<Discrete<C>>, d: FullDynamics<Discrete<D>>, e: FullDynamics<Discrete<E>>, f: FullDynamics<Discrete<F>>, g: FullDynamics<Discrete<G>>, h: FullDynamics<Discrete<H>>, i: FullDynamics<Discrete<I>>, j: FullDynamics<Discrete<J>>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> FullDynamics<Discrete<K>>): FullDynamics<Discrete<K>> = join(map(a, b, c, d, e, f, g, h, i, j, fn))
}

object DiscreteResourceMonad {
    fun <A> pure(a: A): DiscreteResource<A> = ResourceMonad.pure(DiscreteMonad.pure(a))
    fun <A, B> apply(a: DiscreteResource<A>, f: DiscreteResource<(A) -> B>): DiscreteResource<B> =
        ResourceMonad.apply(a, ResourceMonad.map(f, DiscreteMonad::apply))
    fun <A> distribute(a: Discrete<Resource<A>>): DiscreteResource<A> =
        ResourceMonad.map(a.value, DiscreteMonad::pure)
    fun <A> join(a: DiscreteResource<DiscreteResource<A>>): DiscreteResource<A> =
        ResourceMonad.map(ResourceMonad.join(ResourceMonad.map(a, DiscreteResourceMonad::distribute)), DiscreteMonad::join)
    // Auxiliary methods - These are defined only in terms of pure/apply/join above, and can be copied from Monad to Monad
    fun <A, B> apply(f: DiscreteResource<(A) -> B>): (DiscreteResource<A>) -> DiscreteResource<B> = { apply(it, f) }
    fun <A, B> map(a: DiscreteResource<A>, f: (A) -> B): DiscreteResource<B> = apply(a, pure(f))
    fun <A, B> map(f: (A) -> B): (DiscreteResource<A>) -> DiscreteResource<B> = { map(it, f) }
    fun <A, B> bind(a: DiscreteResource<A>, f: (A) -> DiscreteResource<B>): DiscreteResource<B> = join(map(a, f))
    fun <A, B> bind(f: (A) -> DiscreteResource<B>): (DiscreteResource<A>) -> DiscreteResource<B> = { bind(it, f) }
    // Auxiliary map
    fun <A, B, C> map(fn: (A, B) -> C): (DiscreteResource<A>, DiscreteResource<B>) -> DiscreteResource<C> = { a, b -> map(a, b, fn) }
    fun <A, B, C> map(a: DiscreteResource<A>, b: DiscreteResource<B>, fn: (A, B) -> C): DiscreteResource<C> = map(a, b, curry(fn))
    fun <A, B, C> map(a: DiscreteResource<A>, b: DiscreteResource<B>, fn: (A) -> (B) -> C): DiscreteResource<C> = apply(b, map(a, fn))
    fun <A, B, C, D> map(fn: (A, B, C) -> D): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>) -> DiscreteResource<D> = { a, b, c -> map(a, b, c, fn) }
    fun <A, B, C, D> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, fn: (A, B, C) -> D): DiscreteResource<D> = map(a, b, c, curry(fn))
    fun <A, B, C, D> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, fn: (A) -> (B) -> (C) -> D): DiscreteResource<D> = apply(c, map(a, b, fn))
    fun <A, B, C, D, E> map(fn: (A, B, C, D) -> E): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>) -> DiscreteResource<E> = { a, b, c, d -> map(a, b, c, d, fn) }
    fun <A, B, C, D, E> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, fn: (A, B, C, D) -> E): DiscreteResource<E> = map(a, b, c, d, curry(fn))
    fun <A, B, C, D, E> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, fn: (A) -> (B) -> (C) -> (D) -> E): DiscreteResource<E> = apply(d, map(a, b, c, fn))
    fun <A, B, C, D, E, F> map(fn: (A, B, C, D, E) -> F): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>) -> DiscreteResource<F> = { a, b, c, d, e -> map(a, b, c, d, e, fn) }
    fun <A, B, C, D, E, F> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, fn: (A, B, C, D, E) -> F): DiscreteResource<F> = map(a, b, c, d, e, curry(fn))
    fun <A, B, C, D, E, F> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> F): DiscreteResource<F> = apply(e, map(a, b, c, d, fn))
    fun <A, B, C, D, E, F, G> map(fn: (A, B, C, D, E, F) -> G): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>) -> DiscreteResource<G> = { a, b, c, d, e, f -> map(a, b, c, d, e, f, fn) }
    fun <A, B, C, D, E, F, G> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, fn: (A, B, C, D, E, F) -> G): DiscreteResource<G> = map(a, b, c, d, e, f, curry(fn))
    fun <A, B, C, D, E, F, G> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> G): DiscreteResource<G> = apply(f, map(a, b, c, d, e, fn))
    fun <A, B, C, D, E, F, G, H> map(fn: (A, B, C, D, E, F, G) -> H): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>) -> DiscreteResource<H> = { a, b, c, d, e, f, g -> map(a, b, c, d, e, f, g, fn) }
    fun <A, B, C, D, E, F, G, H> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, fn: (A, B, C, D, E, F, G) -> H): DiscreteResource<H> = map(a, b, c, d, e, f, g, curry(fn))
    fun <A, B, C, D, E, F, G, H> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> H): DiscreteResource<H> = apply(g, map(a, b, c, d, e, f, fn))
    fun <A, B, C, D, E, F, G, H, I> map(fn: (A, B, C, D, E, F, G, H) -> I): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>, DiscreteResource<H>) -> DiscreteResource<I> = { a, b, c, d, e, f, g, h -> map(a, b, c, d, e, f, g, h, fn) }
    fun <A, B, C, D, E, F, G, H, I> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, fn: (A, B, C, D, E, F, G, H) -> I): DiscreteResource<I> = map(a, b, c, d, e, f, g, h, curry(fn))
    fun <A, B, C, D, E, F, G, H, I> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> I): DiscreteResource<I> = apply(h, map(a, b, c, d, e, f, g, fn))
    fun <A, B, C, D, E, F, G, H, I, J> map(fn: (A, B, C, D, E, F, G, H, I) -> J): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>, DiscreteResource<H>, DiscreteResource<I>) -> DiscreteResource<J> = { a, b, c, d, e, f, g, h, i -> map(a, b, c, d, e, f, g, h, i, fn) }
    fun <A, B, C, D, E, F, G, H, I, J> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, fn: (A, B, C, D, E, F, G, H, I) -> J): DiscreteResource<J> = map(a, b, c, d, e, f, g, h, i, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> J): DiscreteResource<J> = apply(i, map(a, b, c, d, e, f, g, h, fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> map(fn: (A, B, C, D, E, F, G, H, I, J) -> K): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>, DiscreteResource<H>, DiscreteResource<I>, DiscreteResource<J>) -> DiscreteResource<K> = { a, b, c, d, e, f, g, h, i, j -> map(a, b, c, d, e, f, g, h, i, j, fn) }
    fun <A, B, C, D, E, F, G, H, I, J, K> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, j: DiscreteResource<J>, fn: (A, B, C, D, E, F, G, H, I, J) -> K): DiscreteResource<K> = map(a, b, c, d, e, f, g, h, i, j, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> map(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, j: DiscreteResource<J>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> K): DiscreteResource<K> = apply(j, map(a, b, c, d, e, f, g, h, i, fn))
    // Auxiliary bind
    fun <A, B, C> bind(fn: (A, B) -> DiscreteResource<C>): (DiscreteResource<A>, DiscreteResource<B>) -> DiscreteResource<C> = { a, b -> bind(a, b, fn) }
    fun <A, B, C> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, fn: (A, B) -> DiscreteResource<C>): DiscreteResource<C> = bind(a, b, curry(fn))
    fun <A, B, C> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, fn: (A) -> (B) -> DiscreteResource<C>): DiscreteResource<C> = join(map(a, b, fn))
    fun <A, B, C, D> bind(fn: (A, B, C) -> DiscreteResource<D>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>) -> DiscreteResource<D> = { a, b, c -> bind(a, b, c, fn) }
    fun <A, B, C, D> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, fn: (A, B, C) -> DiscreteResource<D>): DiscreteResource<D> = bind(a, b, c, curry(fn))
    fun <A, B, C, D> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, fn: (A) -> (B) -> (C) -> DiscreteResource<D>): DiscreteResource<D> = join(map(a, b, c, fn))
    fun <A, B, C, D, E> bind(fn: (A, B, C, D) -> DiscreteResource<E>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>) -> DiscreteResource<E> = { a, b, c, d -> bind(a, b, c, d, fn) }
    fun <A, B, C, D, E> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, fn: (A, B, C, D) -> DiscreteResource<E>): DiscreteResource<E> = bind(a, b, c, d, curry(fn))
    fun <A, B, C, D, E> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, fn: (A) -> (B) -> (C) -> (D) -> DiscreteResource<E>): DiscreteResource<E> = join(map(a, b, c, d, fn))
    fun <A, B, C, D, E, F> bind(fn: (A, B, C, D, E) -> DiscreteResource<F>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>) -> DiscreteResource<F> = { a, b, c, d, e -> bind(a, b, c, d, e, fn) }
    fun <A, B, C, D, E, F> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, fn: (A, B, C, D, E) -> DiscreteResource<F>): DiscreteResource<F> = bind(a, b, c, d, e, curry(fn))
    fun <A, B, C, D, E, F> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> DiscreteResource<F>): DiscreteResource<F> = join(map(a, b, c, d, e, fn))
    fun <A, B, C, D, E, F, G> bind(fn: (A, B, C, D, E, F) -> DiscreteResource<G>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>) -> DiscreteResource<G> = { a, b, c, d, e, f -> bind(a, b, c, d, e, f, fn) }
    fun <A, B, C, D, E, F, G> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, fn: (A, B, C, D, E, F) -> DiscreteResource<G>): DiscreteResource<G> = bind(a, b, c, d, e, f, curry(fn))
    fun <A, B, C, D, E, F, G> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> DiscreteResource<G>): DiscreteResource<G> = join(map(a, b, c, d, e, f, fn))
    fun <A, B, C, D, E, F, G, H> bind(fn: (A, B, C, D, E, F, G) -> DiscreteResource<H>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>) -> DiscreteResource<H> = { a, b, c, d, e, f, g -> bind(a, b, c, d, e, f, g, fn) }
    fun <A, B, C, D, E, F, G, H> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, fn: (A, B, C, D, E, F, G) -> DiscreteResource<H>): DiscreteResource<H> = bind(a, b, c, d, e, f, g, curry(fn))
    fun <A, B, C, D, E, F, G, H> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> DiscreteResource<H>): DiscreteResource<H> = join(map(a, b, c, d, e, f, g, fn))
    fun <A, B, C, D, E, F, G, H, I> bind(fn: (A, B, C, D, E, F, G, H) -> DiscreteResource<I>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>, DiscreteResource<H>) -> DiscreteResource<I> = { a, b, c, d, e, f, g, h -> bind(a, b, c, d, e, f, g, h, fn) }
    fun <A, B, C, D, E, F, G, H, I> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, fn: (A, B, C, D, E, F, G, H) -> DiscreteResource<I>): DiscreteResource<I> = bind(a, b, c, d, e, f, g, h, curry(fn))
    fun <A, B, C, D, E, F, G, H, I> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> DiscreteResource<I>): DiscreteResource<I> = join(map(a, b, c, d, e, f, g, h, fn))
    fun <A, B, C, D, E, F, G, H, I, J> bind(fn: (A, B, C, D, E, F, G, H, I) -> DiscreteResource<J>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>, DiscreteResource<H>, DiscreteResource<I>) -> DiscreteResource<J> = { a, b, c, d, e, f, g, h, i -> bind(a, b, c, d, e, f, g, h, i, fn) }
    fun <A, B, C, D, E, F, G, H, I, J> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, fn: (A, B, C, D, E, F, G, H, I) -> DiscreteResource<J>): DiscreteResource<J> = bind(a, b, c, d, e, f, g, h, i, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> DiscreteResource<J>): DiscreteResource<J> = join(map(a, b, c, d, e, f, g, h, i, fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(fn: (A, B, C, D, E, F, G, H, I, J) -> DiscreteResource<K>): (DiscreteResource<A>, DiscreteResource<B>, DiscreteResource<C>, DiscreteResource<D>, DiscreteResource<E>, DiscreteResource<F>, DiscreteResource<G>, DiscreteResource<H>, DiscreteResource<I>, DiscreteResource<J>) -> DiscreteResource<K> = { a, b, c, d, e, f, g, h, i, j -> bind(a, b, c, d, e, f, g, h, i, j, fn) }
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, j: DiscreteResource<J>, fn: (A, B, C, D, E, F, G, H, I, J) -> DiscreteResource<K>): DiscreteResource<K> = bind(a, b, c, d, e, f, g, h, i, j, curry(fn))
    fun <A, B, C, D, E, F, G, H, I, J, K> bind(a: DiscreteResource<A>, b: DiscreteResource<B>, c: DiscreteResource<C>, d: DiscreteResource<D>, e: DiscreteResource<E>, f: DiscreteResource<F>, g: DiscreteResource<G>, h: DiscreteResource<H>, i: DiscreteResource<I>, j: DiscreteResource<J>, fn: (A) -> (B) -> (C) -> (D) -> (E) -> (F) -> (G) -> (H) -> (I) -> (J) -> DiscreteResource<K>): DiscreteResource<K> = join(map(a, b, c, d, e, f, g, h, i, j, fn))
}
